#Most configs are moved to /serverconfig/fluxnetworks-server.toml
placeholder = true

#Jade
[Jade]
	#Displays: Transfer Limit, Priority, Chunk Loading
	enableJadeAdvancedInfo = true
	#Displays: Network Name, Live Transfer Rate & Internal Buffer
	enableJadeBasicInfo = true
	#Display Advanced Info only when sneaking
	enableJadeSneaking = true

